modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="foworld"
version="1.0.2"
displayName="FoWorld"
authors="ii52"
description='''
ii52 Universe: Foworld
new item:Fluorescent_sword
'''

[[dependencies.foworld]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.foworld]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
